"""
Generate a per-cohort RUN_REPORT.md from a completed cohort run (Phase 6).

Reads only the pseudonymised outputs (CohortLevel CSVs, run_manifest.json, Logs/*.json) and writes a
human-readable report next to them. No identifiers are read or written — the report is safe to share.

Usage:
  python scripts/make_run_report.py --cohort-dir "<...>/Outputs/<Validation>/<Cohort>"
"""

from __future__ import annotations

import argparse
import csv
import json
import statistics
from collections import Counter
from pathlib import Path


def _rows(p: Path) -> list[dict]:
    if not p.is_file():
        return []
    with p.open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _fmt_counter(c: Counter, limit: int = 12) -> str:
    if not c:
        return "_none_"
    return ", ".join(f"`{k}` ×{v}" for k, v in c.most_common(limit))


def build(cohort_dir: Path) -> str:
    cl = cohort_dir / "CohortLevel"
    manifest = json.loads((cohort_dir / "run_manifest.json").read_text(encoding="utf-8"))
    summary = {r["metric"]: r["value"] for r in _rows(cl / "cohort_summary.csv")}
    ntcp, tcp = _rows(cl / "ntcp_results.csv"), _rows(cl / "tcp_results.csv")
    qa, fails = _rows(cl / "QA.csv"), _rows(cl / "failures.csv")

    logs = []
    for f in sorted((cohort_dir / "Logs").glob("*.json")):
        try:
            logs.append(json.loads(f.read_text(encoding="utf-8")))
        except Exception:
            continue
    times = [float(r.get("processing_seconds") or 0) for r in logs if r.get("status") == "completed"]

    organs = Counter(r["structure"] for r in ntcp if r.get("structure"))
    targets = Counter(r["structure"] for r in tcp if r.get("structure"))
    reasons = Counter(r["reason_code"] for r in qa if r.get("reason_code"))
    fail_reasons = Counter(r["reason_code"] for r in fails if r.get("reason_code"))
    defn = Counter(r.get("reason_codes") or "(none)" for r in ntcp)

    pkgs = manifest.get("packages", {})
    med = f"{statistics.median(times):.2f}" if times else "n/a"
    tot = f"{sum(times):.0f}" if times else "n/a"

    L = [
        f"# Run report — {manifest.get('cohort')} ({manifest.get('validation')})",
        "",
        "Generated by rbGyanX from pseudonymised outputs only. **No patient identifiers appear in this "
        "report or anywhere in the output tree**; raw IDs live solely in the pseudonym map held outside "
        "this folder.",
        "",
        "## Run identity (traceability)",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Cohort | `{manifest.get('cohort')}` |",
        f"| Input kind | `{manifest.get('input_kind')}` |",
        f"| Engine version | {manifest.get('engine_version')} |",
        f"| Git commit | `{manifest.get('git_commit')}` |",
        f"| Config hash | `{manifest.get('config_hash')}` |",
        f"| Seed | {manifest.get('seed')} |",
        f"| Python | {manifest.get('python')} |",
        f"| numpy / pandas / scipy | {pkgs.get('numpy')} / {pkgs.get('pandas')} / {pkgs.get('scipy')} |",
        f"| pydicom | {pkgs.get('pydicom')} |",
        f"| Started (UTC) | {manifest.get('start_utc')} |",
        f"| Finished (UTC) | {manifest.get('end_utc')} |",
        "",
        "## Cohort outcome",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Patients discovered | {manifest.get('input_inventory', {}).get('n_units_discovered')} |",
        f"| Attempted | {summary.get('attempted', '—')} |",
        f"| **Completed** | **{summary.get('completed', '—')}** |",
        f"| Skipped (documented reduced mode) | {summary.get('skipped', '—')} |",
        f"| Failed | {summary.get('failed', '—')} |",
        f"| Median time / patient | {med} s |",
        f"| Total compute (sum of per-patient) | {tot} s |",
        "",
        "## Results produced",
        "",
        "| Output | Rows |",
        "|---|---|",
        f"| NTCP results | {len(ntcp)} |",
        f"| TCP results | {len(tcp)} |",
        f"| QA reason codes | {len(qa)} |",
        f"| Failures | {len(fails)} |",
        "",
        f"**OARs receiving NTCP:** {_fmt_counter(organs)}",
        "",
        f"**Targets receiving TCP:** {_fmt_counter(targets)}",
        "",
        "## Data-quality reason codes",
        "",
        f"- **QA (per patient):** {_fmt_counter(reasons)}",
        f"- **Failure reasons:** {_fmt_counter(fail_reasons) if fail_reasons else '_none_'}",
        f"- **NTCP definition flags:** {_fmt_counter(defn)}",
        "",
        "## Reproducing this run",
        "",
        "Re-running the same command resumes (completed patients are skipped) and rebuilds the cohort "
        "CSVs identically. See `docs/RUNBOOK.md` for the exact PowerShell per cohort.",
        "",
        "## Files",
        "",
        "- `CohortLevel/` — 16 machine-readable CSVs (stable columns, written even when empty)",
        "- `PatientLevel/<PSEUDONYM>/` — per-patient summary + completion marker",
        "- `Logs/<PSEUDONYM>.json` — status, timing, structures, plan selected, warnings, failure reason",
        "- `QA/phi_scan.json` — automatic identifier scan of this tree (TPS-text cohorts)",
        "- `run_manifest.json` — full provenance",
        "",
    ]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cohort-dir", required=True, type=Path)
    args = ap.parse_args()
    out = args.cohort_dir / "RUN_REPORT.md"
    out.write_text(build(args.cohort_dir), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
