"""Site-specific structure name alias table."""

STRUCTURE_ALIASES: dict[str, list[str]] = {
    # ── TARGET VOLUMES ─────────────────────────────────────────────────────
    "GTV": [
        "gtv",
        "gtvprimary",
        "gtvp",
        "gtvn",
        "gtv1",
        "gtv2",
        "gtv3",
        "gtvprimary",
        "gtvnodal",
        "gtvlung",
        "gtvbreast",
        "gtvbrain",
        "grosstumorvolume",
        "grosstumourvolume",
        "igtv",
        "ictv",
        "gtvmets",
        "gtvmet",
        "brainmet",
        "met",
        "glioma",
        "gbm",
    ],
    "CTV": [
        "ctv",
        "ctvp",
        "ctvn",
        "ctv1",
        "ctv2",
        "ctvhigh",
        "ctvlow",
        "ctvmid",
        "ctv66",
        "ctv54",
        "ctv60",
        "ctv50",
        "ctv45",
        "ctv40",
        "ctvbreast",
        "ctvchestwall",
        "ctvcw",
        "clinicaltargetvolume",
        "ctvwhole",
        "ctvbrain",
        "wbtv",
    ],
    "PTV": [
        "ptv",
        "ptv46gy",
        "ptv46",
        "ptv1",
        "ptv2",
        "ptv66",
        "ptv60",
        "ptv54",
        "ptv50",
        "ptv45",
        "ptv40",
        "ptvhigh",
        "ptvlow",
        "ptvmid",
        "ptvbreast",
        "ptvchestwall",
        "ptvcw",
        "planningtargetvolume",
        "ptv60gy30fr",
        "ptv40gy15fr",
        "ptv45gy25fr",
        "ptvbrainmet",
        "ptvgbm",
        "ptvwb",
    ],
    "ITV": [
        "itv",
        "igtv",
        "internaltargetvolume",
        "internaltarget",
        "igtvlung",
        "itvlung",
    ],
    "BOOST": [
        "boost",
        "gtvboost",
        "ctvboost",
        "ptvboost",
        "lumpectomy",
        "lumpectomycavity",
        "cavity",
        "seroma",
        "tumourbed",
        "tumorbed",
        "surgicalbed",
        "sbrt",
        "gtvsbrt",
        "ptvsbrt",
    ],
    # ── H&N OARs ──────────────────────────────────────────────────────────
    "Parotid_L": [
        "parotidl",
        "ltparotid",
        "leftparotid",
        "parotidleft",
        "parotidglandl",
        "totparotidl",
    ],
    "Parotid_R": [
        "parotidr",
        "rtparotid",
        "rightparotid",
        "parotidrright",
        "parotidglandr",
        "totparotidr",
    ],
    "Submandibular_L": [
        "submandibularl",
        "smgl",
        "ltsmg",
        "leftsmg",
        "submandl",
    ],
    "Submandibular_R": [
        "submandibularr",
        "smgr",
        "rtsmg",
        "rightsmg",
        "submandr",
    ],
    "Mandible": ["mandible", "jaw", "mandibular"],
    "Larynx": ["larynx", "glottic", "supraglottic", "laryngeal"],
    "OralCavity": ["oral", "oralcavity", "oralcav", "mucosa", "oralmucosa"],
    "Pharynx": [
        "pharynx",
        "constrictor",
        "pcm",
        "superiorconstrictor",
        "middleconstrictor",
        "inferiorconstrictor",
        "pharyngealconstrictor",
    ],
    "PharynxConstrictor": [
        "pharynxconstrictor",
        "pharyngealconstrictors",
        "mpc",
        "pcm",
        "constrictormuscle",
        "inferiorpharyngealconstrictor",
    ],
    "Brainstem": ["brainstem", "brainstem", "bs"],
    # ── Lung OARs ─────────────────────────────────────────────────────────
    "Lung_R": ["lungr", "rtlung", "rightlung", "lungrright", "lung r"],
    "Lung_L": ["lungl", "ltlung", "leftlung", "lunglleft", "lung l"],
    "LungTotal": [
        "lungtotal",
        "totallung",
        "bothlungs",
        "lungs",
        "lungbilateral",
        "lungipsi",
        "lungcontra",
        "lungptv",
        "lungtotalminusptv",
    ],
    "Esophagus": ["esophagus", "oesophagus", "esoph", "esophageal"],
    "Trachea": ["trachea", "airway", "tracheal"],
    # ── Breast OARs ───────────────────────────────────────────────────────
    "Breast_Contra": [
        "breastcontra",
        "contralateralbreast",
        "breastl",
        "breastr",
        "oppositebreast",
    ],
    "LAD": ["lad", "leftanteriordescending", "ladcoronary", "ladvessel"],
    "Lung_Ipsi": ["lungipsi", "ipsilaterallung", "lungipsilateral"],
    "Lung_Contra": ["lungcontra", "contralaterallung", "lungcontralateral"],
    "Thyroid": ["thyroid", "thyroidgland", "thyroid_l", "thyroid_r"],
    "BrachialPlexus": [
        "brachialplexus",
        "brachial_plexus",
        "bp_l",
        "bp_r",
        "plexus",
    ],
    "ChestWall": ["chestwall", "chest_wall", "cw", "thoracicwall"],
    "Rib": ["rib", "ribs", "ribcage"],
    # ── Brain OARs ────────────────────────────────────────────────────────
    "Brain": ["brain", "wholebrain", "brainwhole", "brainparenchyma"],
    "NormalBrain": [
        "normalbrain",
        "brain_minus_gtv",
        "brainminusgtv",
        "normal_brain",
        "brainptv",
    ],
    "Hippocampus_L": ["hippocampusl", "hippol", "lefthippocampus"],
    "Hippocampus_R": ["hippocampusr", "hippor", "righthippocampus"],
    "OpticNerve_L": ["opticnervel", "on l", "opticl", "leftonl"],
    "OpticNerve_R": ["opticnerver", "on r", "opticr", "rightonr"],
    "OpticChiasm": ["chiasm", "opticchiasm", "oc"],
    "Pituitary": ["pituitary", "hypophysis", "pituitarygland"],
    "Cochlea_L": ["cochleal", "innearl", "leftcochlea"],
    "Cochlea_R": ["cochlear", "innearr", "rightcochlea"],
    # ── Universal ─────────────────────────────────────────────────────────
    "Rectum": ["rectum", "recto", "rectal"],
    "Bladder": ["bladder", "vesica", "vessie"],
    "Urethra": ["urethra"],
    "BowelBag": ["bowelbag", "bowel_bag", "smallbowel", "bowel"],
    "FemoralHead_L": ["femoralhd_l", "femoral_head_l", "caput_fem_l", "femoralhead_l"],
    "FemoralHead_R": ["femoralhd_r", "femoral_head_r", "caput_fem_r", "femoralhead_r"],
    "Liver": ["liver", "foie", "hepatic", "hcc"],
    "Duodenum": ["duodenum"],
    "Stomach": ["stomach", "magen", "estomac"],
    "Kidney_L": ["kidney_l", "rein_g", "leftkidney"],
    "Kidney_R": ["kidney_r", "rein_d", "rightkidney"],
    "KidneysTotal": ["kidneys", "kidneys_total", "bothkidneys"],
    "SpinalCord": ["spinalcord", "cord", "sc", "spinal"],
    "PRV_Cord": ["prvcord", "cordprv", "prvsc", "scprv"],
    "Heart": ["heart", "cor", "cardiac", "wholeheart"],
    "BODY": ["body", "external", "patient", "skin", "outline"],
    "COUCH": [
        "couch",
        "couchsurface",
        "couchinterior",
        "table",
        "couchbase",
        "indexbar",
        "treatmenttable",
    ],
    "BOLUS": ["bolus", "virtualbolus"],
    "PROSTHESIS": ["prosthesis", "implant", "metalimplant", "hipimplant"],
}
